version: "3.7"
services:
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: secret_marks
    image: secret_marks:latest
    command: [ "/secret_marks/docker/app.sh" ]
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db_app
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev
